#!/bin/bash
read -p "Choose a username: " UN
read -s -p "Choose a password: " PW
echo
read -s -p "Confirm your password: " PWCONF

if [ $PW != $PWCONF ]; then
  echo "Passwords did not match, try again."
  exit 1
fi

echo

sudo docker run -e USERNAME=$UN -e PASSWORD=$PW  -p 80:8080 -d survey_stack

